### ISSUE TITLE
Fatal UI issues

### ISSUE THREAD

**Issue by eesh** [hackidemia/cognimates-training#4]
Looks like the classes page design has been updated. There are some really critical issues:
1. When you add more than one class in either text or vision, you can see the add/remove options when hovering _only_ on the bottom-most class. In the image below, my mouse was hovering over the first class but the add exampes and remove button weren't showing up.
<img width="996" alt="Screenshot 2019-03-14 at 8 39 40 PM" src="https://user-images.githubusercontent.com/1726480/54368132-98435180-4699-11e9-830b-21706488aed1.png">

2. The Add examples and remove buttons are overlapping.
<img width="165" alt="Screenshot 2019-03-14 at 8 39 21 PM" src="https://user-images.githubusercontent.com/1726480/54368148-9d080580-4699-11e9-94ef-930f7e05eccc.png">

3. The buttons on the home page do not expand according to text size. Text sizes in all pages have decreased drastically (unsure if intentional). The Cognimates Studio title in the image below for example, has decreased in size. This is true for all the text in vision_home and possibly text_home. Training pages seem unaffected.
<img width="1177" alt="Screenshot 2019-03-14 at 8 43 18 PM" src="https://user-images.githubusercontent.com/1726480/54368343-fa03bb80-4699-11e9-819c-57ab43ce2a19.png">

**Comment by stefania11** [comment]
What's the status on this @lifeinchords @eesh  I think we can close this issue right?

**Comment by eesh** [comment]
Yes all good now
